server {
    listen 80;
    server_name localhost;
    set $secure_link_secret "YOUR_SECURE_LINK_SECRET";

    # Request to Java
    location /api/ {
        proxy_pass http://vod-app:8080;
        # 紀錄上一個node
        proxy_set_header X-Real-IP $remote_addr;
        # 紀錄整個route
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # [Presigned] Upload video to minio
    location /upload/ {
        proxy_pass http://vod-minio:9000;
        rewrite ^/upload/(.*) /$1 break;
        # 紀錄上一個node
        proxy_set_header X-Real-IP $remote_addr;
        # 紀錄整個route
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # 設置最大上傳限制為 2G
        client_max_body_size 2G;
        # 關閉 Request 緩衝：這會讓 Nginx 像水管一樣，收到一點傳一點
        proxy_request_buffering off;
        # (In) Data -> Nginx 
        proxy_read_timeout 600s;
        # (Out) Nginx -> Data
        proxy_send_timeout 600s;

        # 開啟高效文件傳輸模式 (減少 CPU copy)
        sendfile on;
        # 告訴 TCP 封包要塞滿再發送 (減少網路封包數量)
        tcp_nopush on;
    }

    # [Presigned] Get video from minio
    location ~* "^/hls/(?<token_md5>[^/]+)/(?<token_expires>[^/]+)(?<real_dir>/[^/]+/[^/]+/).*$" {
        # Presigned驗證
        secure_link $token_md5,$token_expires;
        secure_link_md5 "$token_expires!$real_dir!$secure_link_secret";
        if ($secure_link = "") {
            return 403;
        }
        if ($secure_link = "0") {
            return 410;
        }

        # Request丟給minio
        proxy_pass http://vod-minio:9000;
        # ^:字串開始, $:字串結束
        # [^/]:非/的多個字元, +:多個字元 => [^/]+表示非/的多個字元
        # .:任意字元, *:多個, ():捕捉存到$x當中 => (.*)
        # break: 不再進location比對
        rewrite ^/hls/[^/]+/[^/]+/(.*)$ /$1 break;
        # 紀錄上一個node
        proxy_set_header X-Real-IP $remote_addr;
        # 紀錄整個route
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}